dist: trusty
sudo: required

before_install:
  - sudo ./install-dependencies.sh

install:
  - rm -rf public

before_script:
  - sudo ./install-CA.sh

script:
  - /snap/bin/hugo
  - pushd public && htmlproofer --allow-hash-href --alt-ignore /images/gopher-404.jpg --file-ignore /revealjs/ . && popd
